import { useState } from 'react';
import useSWR,{mutate as globalMutate} from 'swr';
import { useNavigate } from 'react-router-dom';
import { ShieldCheck,Check,UserPlus,Merge,ArrowUpRight,MessageSquareMore,X,ClipboardCheck,Sparkles,Send,RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { Btn,Modal,Field } from './Common';
import { api,fetcher,errorText } from '../lib/api';
import { useAuth } from '../lib/auth';
const labels={verify:'Verify this problem',review:'Begin review',reject:'Reject this case',assign:'Assign a responsible admin',request_info:'Request more information',merge:'Merge related cases',escalate:'Escalate this problem',status:'Update problem status'};
export const AdminActions=({problem:p,refresh})=>{
 const {society}=useAuth();const navigate=useNavigate();const {data:community}=useSWR('/community',fetcher);const {data:cases}=useSWR('/problems?status=active',fetcher);
 const [action,setAction]=useState(''),[note,setNote]=useState(''),[status,setStatus]=useState(''),[assignee,setAssignee]=useState(''),[target,setTarget]=useState(''),[busy,setBusy]=useState(false),[official,setOfficial]=useState(''),[error,setError]=useState('');
 const open=a=>{setAction(a);setNote('');setError('');setStatus('');setAssignee('');setTarget('');};
 const execute=async(e,override)=>{e?.preventDefault();setBusy(true);setError('');try{const {data}=await api.post(`/admin/cases/${p.id}/action`,{action:override||action,note:override==='update'?official:note,status,assignee_id:assignee,target_id:target});toast.success(override==='update'?'Official update published':action==='verify'?'Problem verified. Your community can now see the badge.':'Case updated');setAction('');setOfficial('');await refresh();globalMutate(key=>typeof key==='string'&&['/overview','/notifications','/problems','/analytics'].some(k=>key.startsWith(k)));if(data.case_id!==p.id)navigate(`/app/problems/${data.case_id}`);}catch(err){setError(errorText(err));toast.error(errorText(err));}finally{setBusy(false);}};
 return <section className="admin-actions-section" data-testid="admin-actions"><div className="section-heading"><h2><ShieldCheck size={19}/>Administrator workspace</h2><span className="mini-tag">HUMAN DECISION LAYER</span></div><div className="admin-action-grid">{!p.verified&&<Btn id="admin-verify" onClick={()=>open('verify')}><ShieldCheck size={16}/>Verify problem</Btn>}<Btn variant="outline" id="admin-review" onClick={()=>open('review')}><ClipboardCheck size={16}/>Review</Btn><Btn variant="outline" id="admin-assign" onClick={()=>open('assign')}><UserPlus size={16}/>Assign</Btn><Btn variant="outline" id="admin-status" onClick={()=>open('status')}><RefreshCw size={16}/>Update status</Btn><Btn variant="outline" id="admin-request-info" onClick={()=>open('request_info')}><MessageSquareMore size={16}/>Request info</Btn><Btn variant="outline" id="admin-merge" onClick={()=>open('merge')}><Merge size={16}/>Merge</Btn><Btn variant="outline" id="admin-escalate" onClick={()=>open('escalate')}><ArrowUpRight size={16}/>Escalate</Btn><Btn variant="outline" className="danger-text" id="admin-reject" onClick={()=>open('reject')}><X size={16}/>Reject</Btn></div>
 <form onSubmit={e=>execute(e,'update')} className="official-update-form"><label htmlFor="official-update-text">Publish an official update</label><textarea data-testid="official-update-text" id="official-update-text" placeholder="What’s happening, what’s being done, and what residents can expect next." value={official} onChange={e=>setOfficial(e.target.value)} minLength={5} maxLength={3000} required/><div><small>Visible to the community and recorded in the timeline.</small><Btn id="publish-official-update" type="submit" busy={busy}><Send size={14}/>Publish update</Btn></div></form>
 <Modal open={!!action} onClose={()=>setAction('')} title={labels[action]} description={action==='verify'?'Confirm that you have reviewed the community information and supporting evidence. Your name and verification time will be recorded.':action==='merge'?'Reports, evidence, comments, and confirmations move to the selected active case. The source case remains in the audit trail.':'This action will be recorded in the problem timeline.'} id="admin-action-modal"><form className="form-stack" onSubmit={execute}>
 {action==='assign'&&<Field label="Responsible administrator" id="assignee"><select id="assignee" data-testid="assign-admin-select" required value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Choose an administrator</option>{community?.admins.map(a=><option key={a.id} value={a.id}>{a.name} · {a.area}</option>)}</select></Field>}
 {action==='merge'&&<Field label="Merge into" id="merge-target"><select data-testid="merge-target-select" id="merge-target" required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Select a related case</option>{cases?.items.filter(c=>c.id!==p.id).map(c=><option key={c.id} value={c.id}>#{c.case_number} · {c.title}</option>)}</select></Field>}
 {action==='status'&&<Field label="New status" id="new-status"><select data-testid="new-status-select" id="new-status" required value={status} onChange={e=>setStatus(e.target.value)}><option value="">Choose a status</option>{society.settings.statuses.filter(s=>s!=='Verified'&&s!==p.status).map(s=><option key={s} disabled={['Resolved','Closed'].includes(s)&&!p.verified}>{s}</option>)}</select>{!p.verified&&<small>Verify this problem before resolving or closing it.</small>}</Field>}
 {!['verify','review','merge'].includes(action)&&<Field label={['reject','request_info','escalate'].includes(action)?'Reason / information required':'Update note (optional)'} id="action-note"><textarea data-testid="admin-action-note" id="action-note" value={note} onChange={e=>setNote(e.target.value)} required={['reject','request_info','escalate'].includes(action)} minLength={['reject','request_info','escalate'].includes(action)?5:0} maxLength={3000}/></Field>}
 {error&&<p className="form-error" data-testid="admin-action-error">{error}</p>}<div className="form-actions"><Btn type="button" variant="outline" id="cancel-admin-action" onClick={()=>setAction('')}>Cancel</Btn><Btn id="confirm-admin-action" busy={busy} type="submit">{action==='verify'?'Confirm verification':'Confirm action'}<Check size={15}/></Btn></div></form></Modal></section>;
};