import useSWR from 'swr';
import { Link,useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { CloudSun,Cloud,CloudRain,Sun,Wind,Droplets,ArrowUpRight,MapPin,TrafficCone,Plus,Minus,Leaf,Info,Activity } from 'lucide-react';
import { fetcher } from '../lib/api';
import { useAuth } from '../lib/auth';
export const SocietyMap=({problems=[],large=false})=>{
 const {society}=useAuth();const navigate=useNavigate();const [zoom,setZoom]=useState(1);const active=problems.filter(p=>!['Resolved','Closed','Rejected','Merged'].includes(p.status));
 return <div className={`society-map ${large?'large':''}`} data-testid="society-map"><div className="map-scene" style={{transform:`scale(${zoom})`}}><div className="map-park"><span>COMMUNITY<br/>PARK</span><Leaf size={30}/></div><div className="map-road road-horizontal"/><div className="map-road road-vertical"/><div className="map-road road-bottom"/><div className="map-road road-side"/><span className="map-road-label">NORTH GATE AVENUE</span><span className="map-label block-a">BLOCK A</span><span className="map-label block-b">BLOCK B</span><span className="map-label block-c">BLOCK C</span><span className="map-label sector-four">UTILITY JUNCTION</span>{Array.from({length:12},(_,i)=><span aria-hidden="true" key={i} className={`map-building building-${i}`}/>)}{active.slice(0,12).map((p,i)=>{const positions=[[62,30],[68,77],[32,57],[27,28],[78,53],[45,64],[49,44],[17,70],[83,24],[55,85],[16,45],[83,70]];return <button data-testid={`map-pin-${p.id}`} title={`${p.title} · ${p.location}`} className={`map-pin ${p.severity==='High'?'critical':p.verified?'verified':'review'}`} key={p.id} style={{left:`${positions[i][0]}%`,top:`${positions[i][1]}%`}} onClick={()=>navigate(`/app/problems/${p.id}`)}><MapPin size={large?19:15} fill="currentColor"/><span>{p.case_number}</span></button>;})}</div><div className="map-tools"><button data-testid="map-zoom-in" title="Zoom in" disabled={zoom>=1.6} onClick={()=>setZoom(z=>Math.min(1.6,z+.2))}><Plus size={16}/></button><button data-testid="map-zoom-out" title="Zoom out" disabled={zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z-.2))}><Minus size={16}/></button></div><span className="schematic-label" data-testid="map-schematic-label">SCHEMATIC · NOT TO SCALE</span>{large&&<div className="map-location-caption" data-testid="map-coordinates">{society.location} · {society.latitude.toFixed(4)}, {society.longitude.toFixed(4)}</div>}</div>;
};
export const CivicPanels=({problems=[]})=>{
 const {data:civic,error}=useSWR('/civic',fetcher);const {user}=useAuth();if(!civic)return <aside className="civic-panels"><div className="civic-panel" data-testid="civic-load-state">{error?'Civic signals are temporarily unavailable.':'Loading civic signals…'}</div></aside>;
 const {weather:w,aqi:a,traffic:t}=civic;
 return <aside className="civic-panels"><div className="side-section-label"><span className="live-dot"/><strong>YOUR LOCAL PULSE</strong><span>SIMULATED</span></div><section className="civic-panel weather-panel"><div className="civic-panel-heading"><h2><CloudSun size={18}/>Local weather</h2><span className="tiny-label">°C</span></div><p className="civic-location" data-testid="weather-location"><MapPin size={12}/>{civic.location}</p><div className="weather-main"><div><strong data-testid="weather-temperature">{w.temperature}°</strong><span data-testid="weather-condition">{w.condition}</span></div><div className="weather-illustration" aria-hidden="true"><Sun className="weather-sun" size={68} strokeWidth={1.3}/><Cloud className="weather-cloud" size={83} strokeWidth={1.2}/></div></div><div className="weather-minor"><span data-testid="weather-humidity"><Droplets size={13}/> Humidity <strong>{w.humidity}%</strong></span><span data-testid="weather-wind"><Wind size={14}/> Wind <strong>{w.wind} km/h</strong></span></div><div className="forecast">{w.days.map((d,i)=>{const Icon=i===0?CloudSun:i===1?Cloud:CloudRain;return <div key={d.day} data-testid={`forecast-day-${i}`}><span>{d.day}</span><Icon size={22}/><strong>{d.high}° <small>{d.low}°</small></strong></div>;})}</div><p className="forecast-summary" data-testid="forecast-summary">{w.forecast}</p></section>
 <section className="civic-panel aqi-panel"><div className="civic-panel-heading"><h2><Wind size={18}/>Air quality</h2><span className="tiny-label">US AQI</span></div><div className="aqi-main"><strong data-testid="aqi-value">{a.value}</strong><div><span className="aqi-category" data-testid="aqi-category">{a.category}</span><small>Air quality index</small></div><Leaf size={37} strokeWidth={1.25}/></div><div className="aqi-bar"><span/><span/><span/><span/><span/><i style={{left:`${a.value/3}%`}}/></div><div className="aqi-scale"><span>Good</span><span>Hazardous</span></div><div className="pollutants"><span data-testid="aqi-pm25">PM2.5 <strong>{a.pm25} <small>µg/m³</small></strong></span><span data-testid="aqi-pm10">PM10 <strong>{a.pm10} <small>µg/m³</small></strong></span></div><p className="aqi-advisory" data-testid="aqi-advisory"><Info size={14}/>{a.advisory}</p></section>
 <section className="civic-panel traffic-panel"><div className="civic-panel-heading"><h2><TrafficCone size={18}/>On the roads</h2><span className="traffic-live-dot"/></div><div className="traffic-value"><strong data-testid="traffic-condition">{t.condition}</strong><span data-testid="traffic-delay">+{t.delay} min</span></div><p data-testid="traffic-location">{t.area}</p><Link data-testid="traffic-map-link" to="/app/map" className="text-link">View local activity <ArrowUpRight size={14}/></Link></section>
 <section className="civic-panel map-panel"><div className="civic-panel-heading"><h2><MapPin size={18}/>Around your society</h2><Link data-testid="expand-society-map" title="Open society map" to="/app/map"><ArrowUpRight size={18}/></Link></div><SocietyMap problems={problems}/><div className="map-legend"><span><i className="critical"/>High attention</span><span><i className="review"/>Review</span><span><i className="verified"/>Verified</span></div></section>
 <div className="contribution-mini"><span className="contribution-leaf"><Leaf size={23}/></span><div><strong data-testid="sidebar-contribution-points">{user.points} civic points</strong><p>{user.rank} contributor · Making a difference.</p></div><Link data-testid="contribution-profile-link" title="View contribution" to="/app/profile"><ArrowUpRight size={17}/></Link></div></aside>;
};