import { Link } from 'react-router-dom';
import { ArrowRight,Clock,MessageSquare,ThumbsUp,ThumbsDown,Users,MapPin,Sparkles,ShieldCheck,Paperclip,TrafficCone,Lightbulb,Droplets,Trash2,Wrench,ShieldAlert,CloudRain,Bus,Layers } from 'lucide-react';
import { toast } from 'sonner';
import { useState } from 'react';
import { api,errorText,relative } from '../lib/api';
import { useAuth } from '../lib/auth';
import { Status,Verified } from './Common';
import { EvidenceGallery } from './Evidence';
export const categoryIcons={Road:TrafficCone,Traffic:TrafficCone,Water:Droplets,Electricity:Lightbulb,Garbage:Trash2,Maintenance:Wrench,'Public Safety':ShieldAlert,'Weather-related':CloudRain,Transit:Bus,Other:Layers};
export const SignalActions=({problem:p,refresh,compact=false})=>{
 const {user}=useAuth();const [busy,setBusy]=useState(false);
 const act=async changes=>{setBusy(true);try{await api.post(`/problems/${p.id}/signals`,changes);await refresh();}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 return <div className="signal-actions"><button data-testid={`affected-${p.id}`} disabled={busy} className={`affected-button ${p.am_affected?'selected':''}`} onClick={()=>act({affected:!p.am_affected})}><Users size={15}/>{p.am_affected?'You’re affected':'I am affected'}<span>{p.confirmations}</span></button><div className="vote-buttons"><button disabled={busy||p.reporter_id===user.id} data-testid={`upvote-${p.id}`} title={p.reporter_id===user.id?'You cannot vote on your own report':'Support this report'} className={p.my_vote===1?'selected':''} onClick={()=>act({vote:p.my_vote===1?0:1})}><ThumbsUp size={14}/>{p.upvotes}</button><span/><button disabled={busy||p.reporter_id===user.id} data-testid={`downvote-${p.id}`} title="Report does not reflect my experience" className={p.my_vote===-1?'selected':''} onClick={()=>act({vote:p.my_vote===-1?0:-1})}><ThumbsDown size={14}/>{p.downvotes}</button></div>{!compact&&<Link to={`/app/problems/${p.id}#comments`} data-testid={`comments-${p.id}`} className="comment-link"><MessageSquare size={15}/><span>{p.comments_count}</span></Link>}</div>;
};
export const ProblemCard=({problem:p,refresh,isAdmin=false})=>{
 const Icon=categoryIcons[p.category]||Layers;const update=p.official_updates?.slice(-1)[0];return <article className={`problem-card ${p.verified?'is-verified':''}`} data-testid={`problem-card-${p.id}`}><div className="problem-topline"><div className="badges">{p.verified?<Verified id={`verified-${p.id}`}/>:<Status value={p.status} id={`card-status-${p.id}`}/>}<span className={`severity severity-${p.severity.toLowerCase()}`} data-testid={`severity-${p.id}`}>{p.severity==='High'?'High attention':p.severity==='Medium'?'Medium priority':'Standard'}</span></div><span className="case-code" data-testid={`case-number-${p.id}`}>#{p.case_number}</span></div><Link to={`/app/problems/${p.id}`} data-testid={`problem-title-${p.id}`} className="problem-title">{p.title}<ArrowRight size={17}/></Link><div className="problem-meta"><span><Icon size={13}/>{p.category}</span><span className="meta-dot">·</span><span><MapPin size={13}/>{p.location}</span><span className="meta-time"><Clock size={12}/>{relative(p.created_at)}</span></div><p className="problem-description" data-testid={`problem-description-${p.id}`}>{p.description}</p>
 <div className="case-metrics"><div><span>Community reports</span><strong data-testid={`reports-count-${p.id}`}>{p.reports_count}<small> reports</small></strong></div><div><span>Confirmed affected</span><strong data-testid={`affected-count-${p.id}`}>{p.confirmations}<small> residents</small></strong></div><div><span>Supporting evidence</span><strong data-testid={`evidence-count-${p.id}`}>{p.evidence.length}<small> files</small></strong></div></div>
 {p.evidence.length>0&&<EvidenceGallery files={p.evidence} compact caseId={p.id}/>}
 {p.ai&&<div className="ai-strip"><Sparkles size={17}/><div><div className="insight-label"><strong>AI INSIGHT</strong><span>Simulated analysis</span></div><p data-testid={`ai-summary-${p.id}`}>{p.ai.summary}</p></div></div>}
 {update&&<div className="official-strip"><ShieldCheck size={18}/><div><strong>OFFICIAL UPDATE <span>· {update.actor}</span></strong><p data-testid={`official-update-${p.id}`}>{update.text}</p></div></div>}
 <div className="problem-card-footer"><SignalActions problem={p} refresh={refresh}/><Link data-testid={`view-case-${p.id}`} className="view-case" to={`/app/problems/${p.id}`}>{isAdmin?'Review case':'View timeline'}<ArrowRight size={14}/></Link></div><div className="reporter-line" data-testid={`reporter-${p.id}`}>Reported by {p.reporter_name}{p.verified&&<Status value={p.status} id={`verified-card-workflow-${p.id}`}/>}</div></article>;
};