import { useState } from 'react';
import { NavLink,Link,Outlet,useNavigate,useLocation } from 'react-router-dom';
import useSWR from 'swr';
import { LayoutDashboard,ClipboardList,Map,Users,Bell,Settings,LogOut,Plus,ChevronDown,PanelLeftClose,Menu,ShieldCheck,Bookmark,BarChart3,UserCog,ArrowUpRight,Leaf,Activity,FileCheck2,CheckCheck,Loader,User,MailOpen } from 'lucide-react';
import { Brand,Btn } from './Common';
import { useAuth } from '../lib/auth';
import { fetcher,initials } from '../lib/api';
export default function Shell(){
 const {user,society,logout,isAdmin,isOwner}=useAuth();const navigate=useNavigate(),location=useLocation();const [mobile,setMobile]=useState(false);
 const {data:notifications}=useSWR('/notifications',fetcher,{refreshInterval:7000});const {data:overview}=useSWR('/overview',fetcher,{refreshInterval:7000});
 const nav=isAdmin?[[LayoutDashboard,'Overview','/app'],[ClipboardList,'Pull Requests','/app/requests',overview?.new_requests],[Activity,'Active Problems','/app/problems?status=active'],[ShieldCheck,'Verified Problems','/app/problems?status=verified'],[Loader,'In Progress','/app/problems?status=In%20Progress'],[CheckCheck,'Resolved','/app/problems?status=Resolved']]:[[LayoutDashboard,'Dashboard','/app'],[ClipboardList,'Community Problems','/app/problems'],[FileCheck2,'My Reports','/app/my-reports'],[Bookmark,'Following Updates','/app/following'],[Map,'Society Map','/app/map']];
 const navItem=([Icon,title,to,count])=>{const active=to.split('?')[0]===location.pathname&&(!to.includes('?')?(!location.search||location.pathname!=='/app/problems'):new URLSearchParams(to.split('?')[1]).get('status')===new URLSearchParams(location.search).get('status'));return <Link key={to} data-testid={`nav-${title.toLowerCase().replaceAll(' ','-')}`} className={`nav-item ${active?'active':''}`} onClick={()=>setMobile(false)} to={to}><Icon size={18}/><span>{title}</span>{!!count&&<span className="nav-count">{count}</span>}</Link>;};
 return <div className={`workspace ${isAdmin?'admin-workspace':''}`}>
 {mobile&&<button aria-label="Close navigation" data-testid="mobile-nav-overlay" className="mobile-nav-overlay" onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'open':''}`}><div className="sidebar-brand"><Brand/><button data-testid="close-mobile-nav" className="mobile-close" title="Close menu" onClick={()=>setMobile(false)}><PanelLeftClose size={18}/></button></div><div className="workspace-label"><span className="live-dot"/>{isAdmin?'ADMIN WORKSPACE':'COMMUNITY WORKSPACE'}</div><div className="sidebar-society"><span className="society-mini-avatar">{initials(society.name)}</span><div><strong data-testid="sidebar-society-name">{society.name}</strong><span data-testid="sidebar-society-code">{society.code}</span></div><ChevronDown size={14}/></div>
 <div className="nav-group-label">{isAdmin?'OPERATIONS':'YOUR COMMUNITY'}</div><nav className="sidebar-nav">{nav.map(navItem)}</nav><div className="nav-group-label">{isAdmin?'SOCIETY':'PERSONAL'}</div><nav className="sidebar-nav">{navItem([Users,'Community','/app/community'])}{isAdmin&&navItem([BarChart3,'Analytics','/app/analytics'])}{isOwner&&navItem([UserCog,'Admin Management','/app/admins'])}{isOwner&&navItem([Settings,'Settings','/app/settings'])}{!isAdmin&&navItem([User,'My Contribution','/app/profile'])}{navItem([Bell,'Notifications','/app/notifications',notifications?.unread])}</nav>
 <div className="sidebar-bottom"><div className="community-note"><Leaf size={20}/><strong>Community first.</strong><p>A little awareness.<br/>A meaningful difference.</p></div><button data-testid="sidebar-profile" className="sidebar-profile" onClick={()=>{setMobile(false);navigate('/app/profile');}}><span className="avatar">{initials(user.name)}</span><span><strong>{user.name}</strong><small>{isOwner?'Initial Administrator':isAdmin?'Society Administrator':`${user.rank} Contributor`}</small></span><ArrowUpRight size={15}/></button><button className="signout-button" data-testid="logout-button" onClick={async()=>{await logout();navigate('/');}}><LogOut size={15}/> Sign out</button></div></aside>
 <div className="workspace-body"><header className="workspace-header"><div className="header-context"><button className="mobile-menu" data-testid="open-mobile-nav" title="Open menu" onClick={()=>setMobile(true)}><Menu size={22}/></button><span className="header-society-icon">{initials(society.name)}</span><div><div className="header-society-title"><strong data-testid="header-society-name">{society.name}</strong><span className="society-code" data-testid="header-society-code">{society.code}</span></div><span className="header-locality" data-testid="society-location-population">{society.location}<span>·</span>{society.population.toLocaleString()} residents</span></div></div><div className="header-actions"><span className="demo-label" data-testid="simulation-indicator"><span/> SIMULATED CIVIC DATA</span><Link data-testid="header-contribution" to="/app/profile" className="header-contribution" title={`${user.rank} contributor · ${user.points} civic points`}><Leaf size={16}/><strong>{user.points}</strong><span>points · {user.rank}</span></Link><Link to="/app/notifications" data-testid="notification-bell" title="Notifications" className="notification-bell"><Bell size={19}/>{!!notifications?.unread&&<span data-testid="notification-unread-count">{notifications.unread>9?'9+':notifications.unread}</span>}</Link><Link to="/app/profile" data-testid="header-profile" className="avatar small">{initials(user.name)}</Link></div></header><main className="workspace-main" key={location.pathname}><Outlet/></main><footer className="workspace-footer"><span><Activity size={12}/> CityPulse · Community intelligence</span><span>Community signals. Human decisions.</span></footer></div><Link data-testid="mobile-report-button" to="/app/report" className="mobile-report"><Plus size={21}/><span>Report a problem</span></Link></div>;
}