import { useState } from 'react';
import useSWR from 'swr';
import { Link,useNavigate } from 'react-router-dom';
import { ArrowLeft,ArrowRight,Eye,EyeOff,ShieldCheck,Users,Building2,Activity,Check } from 'lucide-react';
import { Brand,Btn,Field } from '../components/Common';
import { api,fetcher,errorText } from '../lib/api';
import { useAuth } from '../lib/auth';
export default function Access({register=false}){
 const {data:demo}=useSWR('/auth/demo',fetcher); const {accept}=useAuth(); const navigate=useNavigate();
 const [form,setForm]=useState({society_code:'',username:'',password:'',name:'',area:''});const [busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async(e,credentials)=>{e?.preventDefault();setBusy(true);setError('');try{const payload=credentials||form;const {data}=await api.post(register?'/auth/register':'/auth/login',register?payload:{society_code:payload.society_code,username:payload.username,password:payload.password});await accept(data);navigate('/app');}catch(err){setError(errorText(err));}finally{setBusy(false);}};
 return <div className="access-page"><header className="public-header"><Brand/><Link data-testid="back-home" to="/"><ArrowLeft size={16}/> Back to CityPulse</Link></header><main className="auth-layout"><div className="auth-story"><span className="eyebrow">A SHARED SENSE OF PLACE</span><h1 data-testid="access-page-title">Your community.<br/>A little closer.</h1><p>Local awareness. Collective action.<br/>A better everyday for everyone.</p><div className="auth-visual"><div className="auth-visual-head"><Activity size={20}/><span>THE COMMUNITY PULSE</span><span className="live-dot"/></div><div className="auth-signal"><div className="signal-graphic"><Building2 size={48} strokeWidth={1}/><div className="signal-line"/><Users size={37} strokeWidth={1}/><div className="signal-line"/><ShieldCheck size={40} strokeWidth={1}/></div><span>Residents</span><span>Intelligence</span><span>Action</span></div><div className="auth-outcome"><span className="circle-check"><Check size={15}/></span> Less noise. More progress.</div></div><p className="auth-note"><ShieldCheck size={16}/> Community signals. Human verification.</p></div>
 <div className="auth-form-wrap"><span className="eyebrow">{register?'BECOME A PART OF IT':'WELCOME BACK'}</span><h2 data-testid="login-heading">{register?'Join your society':'Enter your society'}</h2><p className="muted">{register?'A more connected neighborhood starts with you.':'Stay connected to what matters around you.'}</p><form onSubmit={submit} className="form-stack">
 <Field label="Society code" id="society-code" required><input id="society-code" data-testid="society-code-input" name="society_code" value={form.society_code} onChange={change} placeholder="e.g. GV-48291" required maxLength={30} autoComplete="organization"/></Field>
 {register&&<Field label="Full name" id="full-name" required><input id="full-name" data-testid="register-name-input" name="name" value={form.name} onChange={change} placeholder="Your full name" required minLength={2} maxLength={80}/></Field>}
 <Field label="Username" id="username" required><input id="username" data-testid="username-input" name="username" value={form.username} onChange={change} placeholder="Your username" required minLength={2} maxLength={60} autoComplete="username"/></Field>
 <Field label="Password" id="password" required><div className="password-field"><input id="password" data-testid="password-input" name="password" type={show?'text':'password'} value={form.password} onChange={change} placeholder={register?'At least 8 characters':'Enter your password'} minLength={register?8:1} maxLength={128} autoComplete={register?'new-password':'current-password'} required/><button type="button" title={show?'Hide password':'Show password'} data-testid="toggle-password" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></Field>
 {register&&<Field label="Block / area" id="area"><input id="area" data-testid="register-area-input" name="area" value={form.area} onChange={change} placeholder="e.g. Block B, Apartment 402" maxLength={120}/></Field>}
 {error&&<div className="form-error" role="alert" data-testid="auth-error">{error}</div>}<Btn id="auth-submit" busy={busy} className="wide-btn" type="submit">{register?'Create resident account':'Enter Society'}<ArrowRight size={17}/></Btn></form>
 <p className="auth-switch">{register?'Already part of your society?':'New to your society?'} <Link data-testid="auth-switch-link" to={register?'/enter':'/register'}>{register?'Sign in':'Join as a resident'} <ArrowRight size={13}/></Link></p>
 {!register&&demo&&<div className="demo-access"><div className="demo-access-head"><span className="eyebrow">EXPLORE THE DEMO</span><span className="mini-tag">Sample community</span></div><p>Green Valley Residency · 10,000 residents</p><div className="demo-buttons">{demo.accounts.map(a=><Btn variant="outline" id={`demo-${a.role}`} key={a.username} busy={busy} onClick={()=>submit(null,{society_code:demo.society_code,username:a.username,password:demo.password})}>{a.role==='resident'?<Users size={15}/>:a.role==='admin'?<ShieldCheck size={15}/>:<Building2 size={15}/>} {a.role==='initial_admin'?'Owner':a.role==='admin'?'Admin':'Resident'}</Btn>)}</div><small>Shared demo accounts. Civic readings and AI analysis are simulated.</small></div>}
 </div></main><footer className="auth-footer">A civic workspace, not a social network.<span>Community first. Always.</span></footer></div>;
}