import { useState } from 'react';
import useSWR from 'swr';
import { UserPlus,ShieldCheck,MapPin,Pencil,Trash2,Copy,Eye,EyeOff,Check } from 'lucide-react';
import { toast } from 'sonner';
import { PageHeading,Btn,Field,Modal,Loading,ErrorState } from '../components/Common';
import { useAuth } from '../lib/auth';
import { api,fetcher,errorText,initials } from '../lib/api';
export default function AdminManagement(){
 const {society}=useAuth();const {data,error,mutate}=useSWR('/community',fetcher);const [modal,setModal]=useState(null),[form,setForm]=useState({name:'',username:'',email:'',area:'',categories:[]}),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[credentials,setCredentials]=useState(null),[show,setShow]=useState(false);
 const open=(type,admin)=>{setModal({type,admin});setFailure('');setForm(admin?{area:admin.area,categories:admin.categories}:{name:'',username:'',email:'',area:'',categories:[]});};
 const save=async e=>{e.preventDefault();setBusy(true);setFailure('');try{if(modal.type==='delete'){await api.delete(`/society/admins/${modal.admin.id}`);toast.success('Admin access removed. The account is now a resident.');}else if(modal.type==='edit'){await api.patch(`/society/admins/${modal.admin.id}`,form);toast.success('Responsibilities updated');}else{const {data}=await api.post('/society/admins',form);setCredentials(data);setShow(false);toast.success('Administrator added');}setModal(null);await mutate();}catch(err){setFailure(errorText(err));}finally{setBusy(false);}};
 return <><PageHeading eyebrow="INITIAL ADMIN WORKSPACE" title="The people who keep things moving." description="Assign clear responsibilities and build an administration that scales with your society." action={<Btn id="add-admin-button" onClick={()=>open('add')}><UserPlus size={16}/>Add administrator</Btn>}/><div className="admin-capacity-band"><ShieldCheck size={21}/><span><strong data-testid="admin-capacity">{data?.admins.length??0} of {society.settings.admin_capacity}</strong> administrator seats in use</span><span>Suggested ratio: 1 to {society.settings.admin_ratio.toLocaleString()} residents · Configurable in Settings</span></div>{error?<ErrorState retry={mutate}/>:!data?<Loading/>:<div className="management-list">{data.admins.map(a=><article className="management-row" data-testid={`manage-admin-${a.id}`} key={a.id}><span className="avatar large">{initials(a.name)}</span><div className="management-name"><h3>{a.name}</h3><span>{a.username} · {a.role==='initial_admin'?'Initial administrator':'Administrator'}</span></div><div className="management-area"><span><MapPin size={13}/>{a.area}</span><small>{a.categories.join(', ')||'Society-wide operations'}</small></div><div className="management-load"><strong>{a.workload}</strong><span>active cases</span></div><div className="management-actions"><Btn variant="outline" size="icon" id={`edit-admin-${a.id}`} title="Edit responsibilities" onClick={()=>open('edit',a)}><Pencil size={16}/></Btn>{a.role!=='initial_admin'&&<Btn variant="outline" size="icon" className="danger-text" id={`remove-admin-${a.id}`} title="Remove admin access" onClick={()=>open('delete',a)}><Trash2 size={16}/></Btn>}</div></article>)}</div>}
 <Modal open={!!modal} onClose={()=>setModal(null)} title={modal?.type==='delete'?'Remove administrator access?':modal?.type==='edit'?'Edit responsibilities':'Add an administrator'} description={modal?.type==='delete'?'This user will become a resident. Existing sessions immediately lose admin privileges, and active cases are unassigned.':'Assign an area and categories. Administrators can coordinate across all cases within this society.'} id="admin-management-modal"><form className="form-stack" onSubmit={save}>{modal?.type!=='delete'&&<>{modal?.type==='add'&&<>{[['name','Full name','text'],['username','Username','text'],['email','Email address','email']].map(([name,label,type])=><Field id={`admin-${name}`} label={label} key={name}><input data-testid={`admin-${name}-input`} id={`admin-${name}`} value={form[name]} type={type} onChange={e=>setForm({...form,[name]:e.target.value})} required minLength={name==='username'?3:2} maxLength={name==='name'?80:100}/></Field>)}</>}<Field label="Area / responsibility" id="admin-area"><input data-testid="admin-area-input" id="admin-area" value={form.area} onChange={e=>setForm({...form,area:e.target.value})} placeholder="e.g. Block B and North Gate" maxLength={120} required/></Field><Field label="Categories" id="admin-categories"><div className="category-checkboxes">{society.settings.categories.map(c=><label key={c}><input type="checkbox" data-testid={`admin-category-${c.toLowerCase().replaceAll(' ','-')}`} checked={form.categories.includes(c)} onChange={e=>setForm({...form,categories:e.target.checked?[...form.categories,c]:form.categories.filter(x=>x!==c)})}/>{c}</label>)}</div></Field></>}{failure&&<div data-testid="admin-management-error" className="form-error">{failure}</div>}<div className="form-actions"><Btn variant="outline" type="button" id="cancel-admin-management" onClick={()=>setModal(null)}>Cancel</Btn><Btn busy={busy} id="save-admin-management" type="submit" variant={modal?.type==='delete'?'destructive':'default'}>{modal?.type==='delete'?'Remove admin access':'Save administrator'}</Btn></div></form></Modal>
 <Modal open={!!credentials} onClose={()=>setCredentials(null)} title="Administrator ready" description="Save these credentials securely. The generated password is only shown here." id="admin-credentials-modal">{credentials&&<div className="credentials">{[['Society code',credentials.society_code],['Username',credentials.username],['Password',credentials.password]].map(([label,value],i)=><div className="credential-row" key={label}><span>{label}</span><code data-testid={`admin-credential-${i}`}>{i===2&&!show?'••••••••••••••':value}</code>{i===2&&<button data-testid="admin-credential-toggle" title={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button>}<button data-testid={`copy-admin-credential-${i}`} title={`Copy ${label}`} onClick={async()=>{try{await navigator.clipboard.writeText(value);toast.success('Copied');}catch{toast.error('Please select and copy the value manually');}}}><Copy size={16}/></button></div>)}</div>}<Btn id="close-admin-credentials" onClick={()=>setCredentials(null)}><Check size={16}/>I have saved the credentials</Btn></Modal></>;
}