import { useState } from 'react';
import useSWR from 'swr';
import { ShieldCheck,Users,ThumbsUp,ThumbsDown,MapPin,LockKeyhole,Leaf,ArrowRight } from 'lucide-react';
import { toast } from 'sonner';
import { PageHeading,Loading,ErrorState,Empty } from '../components/Common';
import { useAuth } from '../lib/auth';
import { api,fetcher,errorText,initials } from '../lib/api';
export default function Community(){
 const {society,user}=useAuth();const {data,error,mutate}=useSWR('/community',fetcher);const [busy,setBusy]=useState('');
 const feedback=async(admin,value)=>{setBusy(admin.id);try{await api.post(`/community/admins/${admin.id}/feedback`,{value:admin.my_vote===value?0:value});await mutate();toast.success('Your anonymous feedback has been recorded');}catch(err){toast.error(errorText(err));}finally{setBusy('');}};
 return <><PageHeading eyebrow="THE PEOPLE BEHIND THE PROGRESS" title="A community that shows up." description="Meet the administrators responsible for your neighborhood, and share constructive feedback."/><div className="community-summary"><span className="community-summary-icon"><Users size={34}/></span><div><h2 data-testid="community-society-name">{society.name}</h2><p>{society.location}</p></div><div><strong data-testid="community-population">{society.population.toLocaleString()}</strong><span>Approximate residents</span></div><div><strong data-testid="registered-residents">{data?.registered_residents??'—'}</strong><span>Registered residents{society.demo?' · demo included':''}</span></div><div><strong data-testid="community-admin-count">{data?.admins.length??'—'}</strong><span>Administrators</span></div></div><div className="section-heading"><h2>Society administration</h2><span className="muted">People, responsibilities, and response</span></div>{error?<ErrorState retry={mutate}/>:!data?<Loading/>:!data.admins.length?<Empty title="No administrators found"/>:<div className="admin-directory">{data.admins.map(a=><article className="admin-profile-card" data-testid={`admin-profile-${a.id}`} key={a.id}><div className="admin-profile-top"><span className="avatar large">{initials(a.name)}</span><span className="admin-role-tag"><ShieldCheck size={13}/>{a.role==='initial_admin'?'Initial Admin':'Administrator'}</span></div><h3 data-testid={`admin-name-${a.id}`}>{a.name}</h3><p className="location"><MapPin size={13}/>{a.area}</p><div className="responsibility-tags">{(a.categories.length?a.categories:['Society operations']).map(c=><span key={c}>{c}</span>)}</div><div className="admin-profile-workload"><span>Current workload</span><strong data-testid={`admin-workload-${a.id}`}>{a.workload} active cases</strong></div><div className="reputation-area"><span className="eyebrow">COMMUNITY RESPONSE SCORE</span><div className="reputation-counts"><span data-testid={`admin-positive-${a.id}`}><ThumbsUp size={16}/><strong>{a.positive}</strong> Positive</span><span data-testid={`admin-negative-${a.id}`}><ThumbsDown size={16}/><strong>{a.negative}</strong> Needs attention</span></div>{user.role==='resident'&&<div className="feedback-buttons"><button data-testid={`feedback-positive-${a.id}`} disabled={busy===a.id} className={a.my_vote===1?'selected':''} onClick={()=>feedback(a,1)}><ThumbsUp size={14}/>Responsive</button><button data-testid={`feedback-negative-${a.id}`} disabled={busy===a.id} className={a.my_vote===-1?'selected':''} onClick={()=>feedback(a,-1)}><ThumbsDown size={14}/>Needs improvement</button></div>}</div></article>)}</div>}<div className="privacy-note"><LockKeyhole size={21}/><div><strong>Feedback stays anonymous.</strong><p>Only aggregate response scores are visible. Individual voters are never publicly identified. This is community feedback—not a popularity contest.</p></div></div></>;
}