import { useState } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { ArrowLeft,ArrowRight,Building2,Check,Copy,ShieldCheck,Eye,EyeOff } from 'lucide-react';
import { toast } from 'sonner';
import { Brand,Btn,Field } from '../components/Common';
import { api,errorText } from '../lib/api';
import { useAuth } from '../lib/auth';
export default function CreateSociety(){
 const {accept}=useAuth();const navigate=useNavigate();const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[show,setShow]=useState(false);
 const [form,setForm]=useState({name:'',location:'',address:'',population:10000,latitude:28.4595,longitude:77.0266,admin_name:'',admin_email:'phoenixhx100@gmail.com',admin_capacity:12,admin_ratio:1000});
 const change=e=>setForm({...form,[e.target.name]:['population','latitude','longitude','admin_capacity','admin_ratio'].includes(e.target.name)?e.target.value===''?'':Number(e.target.value):e.target.value});
 const create=async e=>{e.preventDefault();if(step<3){setStep(step+1);return;}setBusy(true);setError('');try{const {data}=await api.post('/societies',form);setResult(data);}catch(err){setError(errorText(err));}finally{setBusy(false);}};
 const copy=async value=>{try{await navigator.clipboard.writeText(value);toast.success('Copied to clipboard');}catch{toast.error('Clipboard unavailable. Please select and copy the value.');}};
 const input=(name,label,type='text',extra={})=><Field label={label} id={name} required><input id={name} data-testid={`create-${name}`} name={name} type={type} value={form[name]} onChange={change} required {...extra}/></Field>;
 return <div className="access-page"><header className="public-header"><Brand/><Link data-testid="create-back-home" to="/"><ArrowLeft size={16}/> Back to CityPulse</Link></header><main className="create-layout">{result?<div className="creation-success"><span className="success-symbol"><Check size={32}/></span><span className="eyebrow">A NEW COMMUNITY CONNECTION</span><h1 data-testid="society-created-heading">Welcome to {result.society.name}.</h1><p>Your society is ready. Save these credentials securely—your generated password is only shown here.</p><div className="credentials">{[['Society code',result.credentials.society_code],['Admin username',result.credentials.username],['Admin password',result.credentials.password]].map(([label,value],i)=><div key={label} className="credential-row"><span>{label}</span><code data-testid={`credential-${i}`}>{i===2&&!show?'••••••••••••••••':value}</code>{i===2&&<button data-testid="credential-toggle-password" title={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button>}<button data-testid={`copy-credential-${i}`} title={`Copy ${label}`} onClick={()=>copy(value)}><Copy size={16}/></button></div>)}</div><div className="info-note"><ShieldCheck size={19}/><span>Share the society code with residents. Keep your administrator username and password private.</span></div><Btn id="enter-created-society" className="wide-btn" onClick={async()=>{await accept(result);navigate('/app');}}>Enter Admin Dashboard <ArrowRight size={16}/></Btn></div>:<><div className="create-heading"><span className="eyebrow">YOUR COMMUNITY STARTS HERE</span><h1 data-testid="create-heading">Bring your society together.</h1><p>One shared space. A more connected neighborhood.</p></div><div className="create-steps">{['Society details','Your administrator','Community settings'].map((s,i)=><button disabled={i+1>step} data-testid={`create-step-${i+1}`} key={s} className={step===i+1?'active':step>i+1?'complete':''} onClick={()=>setStep(i+1)}><span>{step>i+1?<Check size={15}/>:i+1}</span>{s}</button>)}</div><form onSubmit={create} className="create-form form-stack">
 {step===1&&<><h2><Building2 size={21}/> Tell us about your society</h2>{input('name','Society / colony name','text',{placeholder:'e.g. Green Valley Residency',minLength:3,maxLength:100})}<div className="form-grid">{input('location','City / locality','text',{placeholder:'e.g. Sector 14, Gurugram',minLength:3})}{input('population','Approximate population','number',{min:1,max:10000000})}</div>{input('address','Full address','text',{placeholder:'Street, sector, city, postal code',minLength:5})}<div className="form-grid">{input('latitude','Map latitude','number',{step:'any',min:-90,max:90})}{input('longitude','Map longitude','number',{step:'any',min:-180,max:180})}</div><p className="field-note">Coordinates currently point to Gurugram. Update them to your society’s location.</p></>}
 {step===2&&<><h2><ShieldCheck size={21}/> Set up the initial administrator</h2>{input('admin_name','Full name','text',{minLength:2,maxLength:80,placeholder:'Your full name'})}{input('admin_email','Email address','email')}<div className="info-note"><ShieldCheck size={20}/><span>You’ll become the initial administrator. A secure username and password will be generated when your society is created.</span></div></>}
 {step===3&&<><h2><UsersIcon/> A structure that fits your community</h2><div className="form-grid">{input('admin_capacity','Maximum administrators','number',{min:1,max:10000})}{input('admin_ratio','Suggested residents per admin','number',{min:1,max:100000})}</div><div className="info-note"><Building2 size={20}/><span>Based on {Number(form.population).toLocaleString()} residents, your chosen ratio suggests <strong>{Math.ceil(form.population/Math.max(form.admin_ratio,1))} admins</strong>. Your actual capacity stays configurable.</span></div><div className="review-summary"><h3>Ready to connect</h3><p>{form.name} · {form.location}</p><p>{Number(form.population).toLocaleString()} residents · {form.admin_name}</p></div></>}
 {error&&<div className="form-error" data-testid="create-error">{error}</div>}<div className="form-actions">{step>1?<Btn id="create-back" type="button" variant="outline" onClick={()=>setStep(step-1)}><ArrowLeft size={15}/> Back</Btn>:<Link data-testid="create-signin-link" to="/enter">Already have a society?</Link>}<Btn id="create-next" type="submit" busy={busy}>{step===3?'Create Society':'Continue'}<ArrowRight size={16}/></Btn></div></form></>}</main></div>;
}
function UsersIcon(){return <Building2 size={21}/>;}