import { useState,useEffect } from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import useSWR from 'swr';
import { Plus,Search,SlidersHorizontal,ArrowUpRight,ShieldCheck,Activity,CheckCheck,Loader,Inbox,Clock,ArrowRight,Layers,RefreshCw } from 'lucide-react';
import { PageHeading,Btn,Loading,Empty,ErrorState } from '../components/Common';
import { CivicPanels } from '../components/CivicPanels';
import { ProblemCard } from '../components/ProblemCard';
import { useAuth } from '../lib/auth';
import { fetcher } from '../lib/api';
export default function Dashboard({mode='dashboard'}){
 const {user,society,isAdmin}=useAuth();const [params,setParams]=useSearchParams();const status=params.get('status')||'';
 const [search,setSearch]=useState(''),[debounced,setDebounced]=useState(''),[category,setCategory]=useState(''),[sort,setSort]=useState('priority');
 useEffect(()=>{const t=setTimeout(()=>setDebounced(search),250);return()=>clearTimeout(t);},[search]);
 const query=new URLSearchParams({scope:mode==='dashboard'?'':mode,search:debounced,status,category,sort});
 const {data,error,mutate}=useSWR(`/problems?${query}`,fetcher,{refreshInterval:5000});const {data:stats,mutate:refreshStats}=useSWR('/overview',fetcher,{refreshInterval:5000});
 const {data:all}=useSWR('/problems?status=active',fetcher,{refreshInterval:10000});
 const refresh=async()=>{await Promise.all([mutate(),refreshStats()]);};
 const titles={dashboard:isAdmin?'Your community. In good hands.':'Your community, at a glance.',problems:'Community problems',requests:'Admin pull requests',mine:'Your reports. Real impact.',following:'Updates that matter to you.'};
 const descriptions={dashboard:isAdmin?'Review the signal. Verify the facts. Keep your community moving.':'A clearer picture of your neighborhood. A shared path forward.',problems:'Local problems, collective awareness, and visible progress.',requests:'Consolidated community signals, ready for a human decision.',mine:'Your user push requests and the progress they’re making.',following:'Meaningful progress on the problems you’re following.'};
 const statItems=isAdmin?[[Inbox,'New requests',stats?.new_requests,'teal','/app/requests'],[ShieldCheck,'Admin verified',stats?.verified,'green','/app/problems?status=verified'],[Loader,'In progress',stats?.in_progress,'amber','/app/problems?status=In%20Progress'],[CheckCheck,'Resolved',stats?.resolved,'blue','/app/problems?status=Resolved']]:[[Activity,'Active problems',stats?.active,'teal','/app/problems?status=active'],[ShieldCheck,'Admin verified',stats?.verified,'green','/app/problems?status=verified'],[Loader,'In progress',stats?.in_progress,'amber','/app/problems?status=In%20Progress'],[CheckCheck,'Resolved',stats?.resolved,'blue','/app/problems?status=Resolved']];
 const tabs=[['','All problems'],['active','Active'],['verified','Admin verified'],['Under Review','Under review'],['In Progress','In progress'],['Resolved','Resolved']];
 return <><PageHeading eyebrow={mode==='dashboard'?`${isAdmin?'OPERATIONS OVERVIEW':'THE NEIGHBORHOOD BRIEF'} · ${new Date().toLocaleDateString('en-US',{month:'long',day:'numeric'}).toUpperCase()}`:mode==='requests'?'ADMIN PULL REQUESTS':mode==='mine'?'USER PUSH REQUESTS':'COMMUNITY WORKSPACE'} title={titles[mode]||titles.problems} description={descriptions[mode]} action={<Link to="/app/report" data-testid="report-problem-button" className="primary-link"><Plus size={18}/>Report a Problem</Link>}/>
 {mode==='dashboard'&&<div className="stats-grid">{statItems.map(([Icon,label,value,color,to],i)=><Link data-testid={`stat-${label.toLowerCase().replaceAll(' ','-')}`} to={to} className={`stat-card ${color}`} key={label}><div><span>{label}</span><strong data-testid={`stat-value-${i}`}>{value??'—'}</strong><small>{i===0?'In your neighborhood':i===1?'Human-reviewed signals':i===2?'Action is underway':'A better everyday'}</small></div><span className="stat-icon"><Icon size={21}/></span><ArrowUpRight size={15} className="stat-arrow"/></Link>)}</div>}
 {isAdmin&&mode==='dashboard'&&<div className="admin-workload" data-testid="admin-workload"><span><ShieldCheck size={17}/> {user.name} · {user.role==='initial_admin'?'Initial Administrator':'Administrator'}</span><span><strong>{stats?.workload??0}</strong> assigned active cases</span><span><strong>{stats?.under_review??0}</strong> under review</span><span><strong>{stats?.escalated??0}</strong> escalated</span></div>}
 <div className={`dashboard-grid ${mode==='requests'?'queue-grid':''}`}><section className="feed-section"><div className="feed-heading"><div><span className="feed-heading-icon"><Layers size={18}/></span><h2>{mode==='requests'?'Your review queue':mode==='mine'?'My reports':mode==='following'?'Following updates':'Community problems'}</h2><span className="count-bubble" data-testid="feed-count">{data?.total??0}</span></div><button data-testid="refresh-feed" className="refresh-feed" title="Refresh community problems" onClick={refresh}><RefreshCw size={13}/><span>Latest updates</span><span className="live-dot"/></button></div>
 <div className="feed-tabs">{tabs.map(([v,label])=><button key={label} data-testid={`filter-${v.toLowerCase().replaceAll(' ','-')||'all'}`} className={status===v?'active':''} onClick={()=>setParams(v?{status:v}:{})}>{label}</button>)}</div>
 <div className="feed-tools"><div className="search-input"><Search size={16}/><input data-testid="problem-search" aria-label="Search problems" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search problems, locations…"/></div><select data-testid="category-filter" aria-label="Filter category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{society.settings.categories.map(c=><option key={c}>{c}</option>)}</select><select data-testid="sort-filter" aria-label="Sort problems" value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">Priority first</option><option value="recent">Most recent</option></select></div>
 <div className="problem-list">{error?<ErrorState retry={mutate}/>:!data?<Loading/>:data.items.length?data.items.map(p=><ProblemCard key={p.id} problem={p} refresh={refresh} isAdmin={isAdmin}/>):<Empty title={search||category||status?'No matching problems':mode==='mine'?'Your voice can make a difference':mode==='following'?'You’re not following any problems yet':'All clear here'} text={search||category||status?'Try a different search or filter.':mode==='mine'?'When you report a problem, you can track it here.':mode==='following'?'Follow a problem to keep its progress close at hand.':'New civic reports will appear here when your community submits them.'} action={<Link className="text-link" to="/app/report" data-testid="empty-report-link">Report a problem <ArrowRight size={15}/></Link>}/>}</div><p className="feed-end" data-testid="feed-end">You’re up to date. More awareness, less scrolling.</p></section><CivicPanels problems={all?.items||[]}/></div></>;
}