import { useState, useEffect, useCallback, useRef } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowDown, ArrowRight, Building2, Users, Radio, ScanLine, ShieldCheck, CheckCheck, MapPin } from 'lucide-react';
import { Brand } from '../components/Common';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '../components/ui/accordion';
import IntroAnimation from '../components/IntroAnimation';
import DemoPeek from '../components/DemoPeek';
import './intro.css';
const questions=[['What is CityPulse?','A shared civic workspace for your society. Residents report local problems, related reports are organized into cases, and administrators verify and act on them. Everyone sees the outcome.'],['How do I join my society?','Choose Enter Society if you have an account. New residents can register with their society code, a username, and a password. Your society administrator can share the code.'],['What does the AI layer do—and not do?','It groups likely duplicate reports, summarizes community information, and suggests which administrator should review a case. This MVP uses a clearly labeled simulated analysis service. Analysis never verifies an incident or marks it resolved.'],['What happens after I report a problem?','Your user push request joins the community feed. Related reports can be consolidated into one admin pull request. Administrators review evidence, verify the problem, assign a response, and publish progress until resolution.'],['Are weather and air quality readings live?','Weather, US AQI, traffic, and the society map are simulated in this demonstration. They use your society’s configured location, with separate service adapters ready for future live providers. Do not use these readings for safety decisions.'],['How are duplicate or conflicting reports handled?','Likely related reports are grouped into a shared case while retaining original submissions. Conflicting descriptions are flagged for human review. Community confirmations indicate people’s experiences; they are not proof on their own.'],['How do contribution points and admin feedback work?','Useful verified reports, supporting evidence, and confirmations earn configurable points. Residents can submit anonymous administrator feedback, with only aggregate scores shown publicly. There are no public voter lists or popularity leaderboards.'],['Is this another social network?','No followers, entertainment posts, or endless scrolling. CityPulse is built around problems, reliable updates, and outcomes. Notifications are reserved for meaningful changes to the cases that matter to you.']];
export default function Landing(){
  const [intro]=useState(()=>{try{if(typeof window==='undefined')return{play:false,reduced:false};const reduced=!!(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches);let seen=false;try{seen=!!localStorage.getItem('citypulse-intro-v1');}catch{seen=false;}return{play:!reduced&&!seen,reduced};}catch{return{play:false,reduced:false};}});
  const [phase,setPhase]=useState(intro.play?'intro':'done');
  const reveal=useCallback(()=>setPhase(p=>p==='intro'?'reveal':p),[]);
  const complete=useCallback(()=>{setPhase('done');try{localStorage.setItem('citypulse-intro-v1','1');}catch{/* ignore */}},[]);
  useEffect(()=>{if(!intro.play)return undefined;const t=setTimeout(()=>setPhase('done'),6500);return()=>clearTimeout(t);},[intro.play]);
  const heroClass=phase==='intro'?'cp-hide':(intro.reduced?'':'cp-reveal');
  const heroRef=useRef(null);
  useEffect(()=>{
    if(intro.reduced)return undefined;
    let raf=0;
    const onScroll=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const el=heroRef.current;if(!el)return;const h=el.offsetHeight||1;const p=Math.min(1,Math.max(0,window.scrollY/h));el.style.setProperty('--p',p.toFixed(4));});};
    window.addEventListener('scroll',onScroll,{passive:true});
    onScroll();
    return()=>{window.removeEventListener('scroll',onScroll);if(raf)cancelAnimationFrame(raf);};
  },[intro.reduced]);
  return <div className="landing"><header className="public-header"><Brand/><nav><a data-testid="nav-how-it-works" href="#how-it-works">How it works</a><a data-testid="nav-faq" href="#faq">FAQs</a><Link data-testid="nav-enter" to="/enter">Enter Society <ArrowUpRight size={15}/></Link><Link data-testid="nav-create" className="public-primary" to="/create">Create Society <ArrowRight size={15}/></Link></nav></header>
  <section ref={heroRef} className={`landing-hero ${heroClass}`} data-testid="landing-hero" data-future-animation-slot="city-introduction">{intro.play&&phase!=='done'&&<IntroAnimation onReveal={reveal} onComplete={complete}/>}<img src="/assets/city-neighborhood.jpg" alt="An aerial view of a connected urban neighborhood" className="hero-image"/><div className="hero-shade"/><div className="hero-copy"><span className="hero-eyebrow" data-testid="hero-eyebrow"><span/> CONNECTED COMMUNITIES. BETTER EVERYDAYS.</span><h1 data-testid="hero-title"><span className="hero-line hero-line-1">A better neighborhood.</span><br/><span className="hero-line hero-line-2">Starts with <em>us.</em></span></h1><p data-testid="hero-description">Know what’s happening. Make yourself heard.<br/>Turn community signals into meaningful action.</p><Link to="/enter" className="hero-cta" data-testid="hero-enter">Find your community <ArrowUpRight size={19}/></Link></div><div className="hero-footer"><a href="#society-access" data-testid="hero-scroll"><ArrowDown size={15}/> A little awareness. A lasting difference.</a><span><MapPin size={13}/> A more connected city, one society at a time.</span></div><div className="hero-index" aria-hidden="true">01 — CITYPULSE</div></section>
  <section className="society-access-band" id="society-access"><div className="access-intro"><span className="eyebrow">YOUR NEIGHBORHOOD, CONNECTED</span><h2 data-testid="access-heading">Good things happen<br/>when we act together.</h2><p>Understand what is happening around you.<br/>Report problems. Let AI organize the signal.<br/>Help your community and administrators act faster.</p></div><Link to="/enter" className="access-option" data-testid="enter-society-card"><span className="option-icon"><Users size={25}/></span><span className="option-number">01</span><h3>Enter your society</h3><p>Your community. Your local updates.<br/>Your place to make a difference.</p><span className="option-link">Enter Society <ArrowUpRight size={20}/></span></Link><Link to="/create" className="access-option" data-testid="create-society-card"><span className="option-icon"><Building2 size={25}/></span><span className="option-number">02</span><h3>Bring your society together</h3><p>Create a shared space for your residents<br/>and the people who keep things running.</p><span className="option-link">Create Society <ArrowUpRight size={20}/></span></Link></section>
  <section className="how-band" id="how-it-works"><div className="section-title"><span className="eyebrow">FROM A SIGNAL TO A SOLUTION</span><h2>A clear path to a better everyday.</h2></div><div className="steps">{[[Radio,'You report','A pothole. A water leak. Something your community needs to know.'],[ScanLine,'Signals connect','Related reports become one clear, structured case.'],[ShieldCheck,'Admins act','People verify the facts, coordinate a response, and take responsibility.'],[CheckCheck,'Everyone knows','Official updates and a transparent timeline, all the way to resolution.']].map(([Icon,title,text],i)=><div className="step" key={title}><div className="step-top"><Icon size={24}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></div>)}</div></section>
  <DemoPeek/>
  <section className="faq-section" id="faq"><div><span className="eyebrow">A LITTLE MORE CLARITY</span><h2>Good questions.<br/>Straight answers.</h2><p>Built for civic action.<br/>Not for distraction.</p></div><Accordion type="single" collapsible className="faq-list">{questions.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger data-testid={`faq-question-${i}`}>{q}</AccordionTrigger><AccordionContent data-testid={`faq-answer-${i}`}>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
  <footer className="public-footer"><Brand id="footer-citypulse-brand"/><p>Community is not a place. It’s what we do together.</p><span>CityPulse · Civic intelligence</span></footer></div>;}