import { useState,useEffect } from 'react';
import { Link,useParams,useNavigate } from 'react-router-dom';
import useSWR from 'swr';
import { ArrowLeft,MapPin,Clock,Bookmark,BookmarkCheck,ShieldCheck,Sparkles,MessageSquare,Send,ThumbsUp,Users,Paperclip,FileText,Info,AlertTriangle,Check,ArrowRight } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../lib/auth';
import { api,fetcher,errorText,relative,initials } from '../lib/api';
import { Btn,Status,Verified,Loading,ErrorState } from '../components/Common';
import { SignalActions } from '../components/ProblemCard';
import { EvidenceGallery } from '../components/Evidence';
import { AdminActions } from '../components/AdminActions';
export default function ProblemDetail(){
 const {id}=useParams(),navigate=useNavigate();const {isAdmin,user}=useAuth();const {data:p,error,mutate}=useSWR(`/problems/${id}`,fetcher,{refreshInterval:5000});const [comment,setComment]=useState(''),[busy,setBusy]=useState(false),[showReports,setShowReports]=useState(false);
 useEffect(()=>{if(p?.merged_into)navigate(`/app/problems/${p.merged_into}`,{replace:true});},[p?.merged_into,navigate]);
 const follow=async()=>{try{await api.post(`/problems/${id}/signals`,{following:!p.following});mutate();toast.success(p.following?'You’ve unfollowed this problem':'You’ll receive meaningful updates on this problem');}catch(err){toast.error(errorText(err));}};
 const submitComment=async e=>{e.preventDefault();setBusy(true);try{await api.post(`/problems/${id}/comments`,{text:comment});setComment('');await mutate();toast.success('Your observation was added');}catch(err){toast.error(errorText(err));}finally{setBusy(false);}};
 if(error)return <ErrorState retry={mutate}/>;if(!p)return <Loading/>;
 return <><Link className="back-link" data-testid="back-to-problems" to={isAdmin?'/app/requests':'/app/problems'}><ArrowLeft size={15}/> {isAdmin?'Back to review queue':'Back to community problems'}</Link><div className="detail-header"><div className="detail-badges"><span className="case-code" data-testid="detail-case-id">{isAdmin?'ADMIN PULL REQUEST':'COMMUNITY CASE'} #{p.case_number}</span>{p.verified?<Verified id="detail-verified-badge"/>:<span className="community-label">COMMUNITY SIGNAL</span>}<Status value={p.status} id="detail-status"/></div><h1 data-testid="detail-title">{p.title}</h1><div className="detail-meta"><span><MapPin size={15}/>{p.location}</span><span><Clock size={14}/>{new Date(p.created_at).toLocaleString()}</span><span>Reported by {p.reporter_name}</span><span className="mini-tag">{p.category}</span></div></div>
 <div className="detail-grid"><div className="detail-main"><section className="detail-section"><div className="section-heading"><h2><FileText size={18}/>The community report</h2>{p.demo&&<span className="mini-tag" data-testid="demo-case-label">DEMO SCENARIO</span>}</div><p className="detail-description" data-testid="detail-description">{p.description}</p><div className="detail-observation"><span><small>Observed duration</small><strong data-testid="detail-duration">{p.duration||'Not specified'}</strong></span><span><small>Affected area</small><strong data-testid="detail-affected-area">{p.affected_area||p.location}</strong></span></div><div className="detail-stats">{[[FileText,p.reports_count,'Community reports'],[Users,p.confirmations,'Residents affected'],[Paperclip,p.evidence.length,'Evidence files'],[MessageSquare,p.comments_count,'Observations']].map(([Icon,value,label],i)=><div key={label}><Icon size={18}/><strong data-testid={`detail-stat-${i}`}>{value}</strong><span>{label}</span></div>)}</div><p className="signal-disclaimer"><Info size={13}/>Community signals add context. Counts alone are not proof.</p><div className="detail-actions"><SignalActions problem={p} refresh={mutate} compact/><Btn variant="outline" id="follow-updates-button" onClick={follow}>{p.following?<BookmarkCheck size={16}/>:<Bookmark size={16}/>} {p.following?'Following updates':'Follow updates'}</Btn></div></section>
 {p.evidence.length>0&&<section className="detail-section"><div className="section-heading"><h2><Paperclip size={18}/>Supporting evidence</h2><span className="count-bubble">{p.evidence.length}</span></div><EvidenceGallery files={p.evidence} caseId={id}/></section>}
 <section className="detail-section ai-detail"><div className="section-heading"><h2><Sparkles size={19}/>AI situation summary</h2><span className="mini-tag" data-testid="ai-simulated-label">SIMULATED ANALYSIS</span></div><p data-testid="detail-ai-summary">{p.ai?.summary}</p><div className="ai-findings"><div><small>Suggested category</small><strong data-testid="ai-category">{p.ai?.suggested_category}</strong></div><div><small>Suggested administrator</small><strong data-testid="ai-admin">{p.ai?.suggested_admin}</strong></div><div><small>Reported disruption</small><strong data-testid="ai-duration">{p.ai?.duration}</strong></div><div><small>Community observations analyzed</small><strong data-testid="ai-comments">{p.ai?.comment_count??0}</strong></div></div><div className="correlation-note"><Info size={16}/><p data-testid="ai-correlation">{p.ai?.related_signal}</p></div>{p.ai?.contradictions?.map((c,i)=><div className="contradiction-note" key={c} data-testid={`ai-contradiction-${i}`}><AlertTriangle size={16}/>{c}</div>)}<button className="text-link" data-testid="toggle-source-reports" onClick={()=>setShowReports(!showReports)}>{showReports?'Hide':'View'} consolidated source reports ({p.reports_count}) <ArrowRight size={14}/></button>{showReports&&<div className="source-reports">{p.reports?.map((r,i)=><article data-testid={`source-report-${i}`} key={r.id}><strong>{r.reporter_name} <small>{relative(r.created_at)}</small></strong><p>{r.description}</p></article>)}</div>}</section>
 {isAdmin&&<AdminActions problem={p} refresh={mutate}/>}
 {p.official_updates?.length>0&&<section className="detail-section"><div className="section-heading"><h2><ShieldCheck size={19}/>Official updates</h2></div>{[...p.official_updates].reverse().map((u,i)=><div className="official-update-block" data-testid={`official-update-block-${i}`} key={u.id}><div><span><ShieldCheck size={15}/>{u.actor}</span><small>{new Date(u.created_at).toLocaleString()}</small></div><p>{u.text}</p></div>)}</section>}
 <section className="detail-section comments-section" id="comments"><div className="section-heading"><h2><MessageSquare size={18}/>Community observations</h2><span className="count-bubble">{p.comments_count}</span></div>{p.comments?.map(c=><article className="comment" data-testid={`comment-${c.id}`} key={c.id}><span className="avatar">{initials(c.author_name)}</span><div><div className="comment-heading"><strong>{c.author_name}</strong><small>{relative(c.created_at)}</small></div><p data-testid={`comment-text-${c.id}`}>{c.text}</p><button data-testid={`helpful-${c.id}`} title="Mark this observation helpful" disabled={c.author_id===user.id} className={c.my_helpful?'selected':''} onClick={async()=>{try{await api.post(`/comments/${c.id}/helpful`);mutate();}catch(err){toast.error(errorText(err));}}}><ThumbsUp size={12}/>Helpful {c.helpful_count||''}</button></div></article>)}{!p.comments_count&&<p className="muted">No observations yet.</p>}{!['Closed','Rejected','Merged'].includes(p.status)&&<form className="comment-form" onSubmit={submitComment}><textarea data-testid="comment-input" aria-label="Community observation" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add useful details, a recent observation, or additional context…" required minLength={2} maxLength={2000}/><Btn id="submit-comment" type="submit" busy={busy}><Send size={15}/>Add observation</Btn></form>}</section></div>
 <aside className="timeline-panel"><div className="timeline-heading"><span className="timeline-heading-icon"><Clock size={20}/></span><div><span className="eyebrow">TRANSPARENT BY DESIGN</span><h2>Updates on this problem</h2></div></div><div className="timeline-current"><small>CURRENT STATUS</small><Status value={p.status} id="timeline-current-status"/>{p.verified&&<p data-testid="verification-record"><ShieldCheck size={14}/>Verified by {p.verified_by}<br/>{new Date(p.verified_at).toLocaleString()}</p>}{p.assigned_name&&<p data-testid="case-assigned-to">Assigned to <strong>{p.assigned_name}</strong></p>}</div><div className="timeline">{[...p.timeline].reverse().map((e,i)=><article className={`timeline-event timeline-${e.kind}`} data-testid={`timeline-event-${i}`} key={e.id}><div className="timeline-node">{e.kind==='verified'?<Check size={11}/>:e.kind==='ai'?<Sparkles size={10}/>:null}</div><small>{new Date(e.created_at).toLocaleDateString('en-US',{month:'short',day:'numeric'})} · {new Date(e.created_at).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</small><strong>{e.kind==='official'?'OFFICIAL UPDATE':e.kind==='verified'?'ADMIN VERIFIED':e.kind==='ai'?'AI INSIGHT':'COMMUNITY SIGNAL'}</strong><p data-testid={`timeline-text-${i}`}>{e.text}</p><span>{e.actor}{e.source_case_number?` · Source #${e.source_case_number}`:''}</span></article>)}</div><div className="timeline-footer"><ShieldCheck size={15}/><p>Every step stays visible.<br/>Only administrators verify and resolve.</p></div></aside></div></>;
}