import { useState,useRef } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { Upload,FileImage,X,ArrowLeft,ArrowRight,ShieldCheck,MapPin,CheckCircle2,Info,Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { mutate } from 'swr';
import { useAuth } from '../lib/auth';
import { api,errorText } from '../lib/api';
import { PageHeading,Btn,Field } from '../components/Common';
const localTime=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function ReportProblem(){
 const {society}=useAuth();const navigate=useNavigate();const fileInput=useRef(null);const [form,setForm]=useState({title:'',description:'',category:'',location:'',observed_at:localTime(),duration:'',affected_area:''});const [files,setFiles]=useState([]),[uploading,setUploading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const upload=async e=>{const selected=Array.from(e.target.files||[]);e.target.value='';if(files.length+selected.length>5){toast.error('You can attach up to 5 evidence files');return;}setUploading(true);for(const file of selected){if(file.size>10*1024*1024){toast.error(`${file.name} exceeds 10 MB`);continue;}const payload=new FormData();payload.append('file',file);try{const {data}=await api.post('/files',payload);setFiles(f=>[...f,data]);}catch(err){toast.error(errorText(err));}}setUploading(false);};
 const remove=async f=>{try{await api.delete(`/files/${f.id}`);setFiles(list=>list.filter(x=>x.id!==f.id));}catch(err){toast.error(errorText(err));}};
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const {data}=await api.post('/problems',{...form,observed_at:new Date(form.observed_at).toISOString(),evidence_ids:files.map(f=>f.id)});toast.success('Your problem has been submitted.',{description:data.clustered?'Your report was grouped with a related community case.':'Your user push request is now in the community workflow.'});await mutate(key=>typeof key==='string'&&(key.startsWith('/problems')||key==='/overview'||key==='/notifications'));navigate(`/app/problems/${data.case_id}`);}catch(err){setError(errorText(err));}finally{setBusy(false);}};
 return <><Link data-testid="report-back" to="/app" className="back-link"><ArrowLeft size={15}/>Back to your community</Link><PageHeading eyebrow="USER PUSH REQUEST" title="A small report. A meaningful step." description="Tell your community what’s happening. Clear details help the right people act."/><div className="report-layout"><form className="report-form form-stack" onSubmit={submit}><section><div className="section-heading"><h2><FileImage size={19}/>Problem details</h2><span className="muted">* Required</span></div><Field label="Problem title" id="report-title" required><input data-testid="report-title-input" id="report-title" name="title" value={form.title} onChange={change} placeholder="e.g. Water leak near the Block A entrance" minLength={5} maxLength={150} required/></Field><div className="form-grid"><Field label="Category" id="report-category" required><select data-testid="report-category-select" id="report-category" name="category" value={form.category} onChange={change} required><option value="">Select a category</option>{society.settings.categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Location" id="report-location" required><input data-testid="report-location-input" id="report-location" name="location" value={form.location} onChange={change} placeholder="Block, street, or a nearby landmark" required minLength={3} maxLength={150}/></Field></div><Field label="What’s happening?" id="report-description" required><textarea data-testid="report-description-input" id="report-description" name="description" value={form.description} onChange={change} placeholder="Describe what you observed, where it happened, and how it affects the community." required minLength={15} maxLength={5000}/></Field></section>
 <section><div className="section-heading"><h2><MapPin size={18}/>A little more context</h2></div><div className="form-grid"><Field label="When did you observe it?" id="report-observed" required><input data-testid="report-observed-input" id="report-observed" type="datetime-local" name="observed_at" value={form.observed_at} onChange={change} max={localTime()} required/></Field><Field label="Observed duration" id="report-duration"><input data-testid="report-duration-input" id="report-duration" name="duration" value={form.duration} onChange={change} placeholder="e.g. For the last 2 hours" maxLength={120}/></Field></div><Field label="Affected area (optional)" id="report-affected-area"><input data-testid="report-affected-area-input" id="report-affected-area" name="affected_area" value={form.affected_area} onChange={change} placeholder="e.g. Blocks A and B, North Gate" maxLength={150}/></Field></section>
 <section><div className="section-heading"><h2><Upload size={18}/>Supporting evidence</h2><span className="muted">Optional</span></div><input type="file" ref={fileInput} data-testid="evidence-file-input" className="file-input" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple onChange={upload} disabled={uploading||files.length>=5}/><button className="upload-zone" data-testid="upload-evidence-button" type="button" onClick={()=>fileInput.current?.click()} disabled={uploading||files.length>=5}>{uploading?<Loader2 className="spin" size={27}/>:<Upload size={27}/>}<strong>{uploading?'Uploading evidence…':'Add a photo or video'}</strong><span>JPG, PNG, WebP, MP4, WebM · Up to 10 MB each · 5 files maximum</span></button>{files.map(f=><div className="uploaded-file" data-testid={`uploaded-file-${f.id}`} key={f.id}><CheckCircle2 size={17}/><span>{f.original_filename}</span><button type="button" title="Remove evidence" data-testid={`remove-file-${f.id}`} onClick={()=>remove(f)}><X size={16}/></button></div>)}</section>
 {error&&<div className="form-error" data-testid="report-error">{error}</div>}<div className="form-actions"><Link data-testid="cancel-report" to="/app">Cancel</Link><Btn id="submit-problem-button" type="submit" busy={busy} disabled={uploading}>Submit problem <ArrowRight size={16}/></Btn></div></form><aside className="report-guidance"><span className="guidance-icon"><ShieldCheck size={31}/></span><h2>Useful details.<br/>Better responses.</h2><p>Your report becomes a signal that your community and administrators can act on.</p><div><span>01</span><p>Share what you personally observed. Facts make the difference.</p></div><div><span>02</span><p>Related reports are organized into one case, so nothing gets lost in the noise.</p></div><div><span>03</span><p>Administrators verify the situation. You can follow every step in the timeline.</p></div><div className="emergency-note"><Info size={18}/><p>For an immediate emergency, contact your local emergency services. CityPulse is not an emergency dispatch service.</p></div></aside></div></>;
}